name: Build and Push to GHCR

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push the Image to GHCR
        run: |
          docker login ghcr.io -u ${{ github.actor }} \
          -p $
          docker build -t ghcr.io/${{ github.actor }}/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.actor }}/${{ github.repository }}:latest